import {
  Agent,
  AgentRun,
  ApprovalRequest,
  ConnectedApp,
  Conversation,
  Memory,
  Message,
  ObservabilityRun,
  ScheduledTask,
  SystemHealthSummary,
  SystemSettings,
} from './types';

export const MOCK_AGENTS: Agent[] = [
  {
    id: 'agent_supervisor',
    name: 'Nexus Supervisor',
    role: 'supervisor',
    description: 'High-level goal decomposition, routing, and synthesis coordinator',
    status: 'idle',
    model: 'gemini-3.8-flash',
    capabilities: [
      { id: 'c1', name: 'Task Planning', description: 'Decompose goals into subtasks', mcpServer: 'core', requiresApproval: false },
      { id: 'c2', name: 'Agent Delegation', description: 'Route sub-goals to specialized workers', mcpServer: 'core', requiresApproval: false },
    ],
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-30T10:00:00Z',
  },
  {
    id: 'agent_comms',
    name: 'Comms Agent',
    role: 'comms_agent',
    description: 'Email drafting, thread summarization, and Telegram communications',
    status: 'idle',
    model: 'gemini-3.8-flash',
    capabilities: [
      { id: 'c3', name: 'Gmail Read', description: 'Search threads and messages', mcpServer: 'mcp-gmail', requiresApproval: false },
      { id: 'c4', name: 'Gmail Send', description: 'Send external emails', mcpServer: 'mcp-gmail', requiresApproval: true },
      { id: 'c5', name: 'Telegram Send', description: 'Post channel & direct updates', mcpServer: 'mcp-telegram', requiresApproval: true },
    ],
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-30T10:00:00Z',
  },
  {
    id: 'agent_calendar',
    name: 'Calendar Agent',
    role: 'calendar_agent',
    description: 'Executive scheduling, conflict resolution, and buffer management',
    status: 'idle',
    model: 'gemini-3.8-flash',
    capabilities: [
      { id: 'c6', name: 'Calendar Availability', description: 'Query free-busy slots', mcpServer: 'mcp-calendar', requiresApproval: false },
      { id: 'c7', name: 'Calendar Booking', description: 'Create and update calendar invites', mcpServer: 'mcp-calendar', requiresApproval: true },
    ],
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-30T10:00:00Z',
  },
  {
    id: 'agent_browser',
    name: 'Browser Agent',
    role: 'browser_agent',
    description: 'Playwright headless web navigation, data extraction, and form operations',
    status: 'idle',
    model: 'gemini-3.8-flash',
    capabilities: [
      { id: 'c8', name: 'Web Scraping', description: 'Navigate and extract clean markdown', mcpServer: 'mcp-playwright', requiresApproval: false },
      { id: 'c9', name: 'Form Automation', description: 'Click and enter web credentials', mcpServer: 'mcp-playwright', requiresApproval: true },
    ],
    createdAt: '2026-09-05T00:00:00Z',
    updatedAt: '2026-09-30T10:00:00Z',
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv_1',
    title: 'Board Meeting Prep & Calendar Audit',
    createdAt: '2026-09-30T14:30:00Z',
    updatedAt: '2026-09-30T16:45:00Z',
    lastMessagePreview: 'I have verified your calendar and drafted the agenda recap for Sarah.',
    messageCount: 5,
    activeAgentId: 'agent_supervisor',
    pinned: true,
    tags: ['Executive', 'Calendar', 'Board'],
  },
  {
    id: 'conv_2',
    title: 'Quarterly Cloud Budget Analysis',
    createdAt: '2026-09-29T11:15:00Z',
    updatedAt: '2026-09-29T11:45:00Z',
    lastMessagePreview: 'Infrastructure spend rose 12% due to vector indexing batch jobs.',
    messageCount: 4,
    activeAgentId: 'agent_browser',
    pinned: false,
    tags: ['Finance', 'Infrastructure'],
  },
  {
    id: 'conv_3',
    title: 'Weekly Team Standup Digest',
    createdAt: '2026-09-28T09:00:00Z',
    updatedAt: '2026-09-28T09:12:00Z',
    lastMessagePreview: 'Sent the 5-bullet summary to the Telegram core dev group.',
    messageCount: 3,
    activeAgentId: 'agent_comms',
    pinned: false,
    tags: ['Digest', 'Telegram'],
  },
];

export const MOCK_MESSAGES: Message[] = [
  {
    id: 'msg_1',
    conversationId: 'conv_1',
    role: 'user',
    content: 'Good morning. Check my unread emails from the board members, see if anyone asked to move our Friday prep meeting, and give me a clear action summary.',
    createdAt: '2026-09-30T14:30:00Z',
  },
  {
    id: 'msg_2',
    conversationId: 'conv_1',
    role: 'assistant',
    content: `I've analyzed your inbox and cross-referenced with your calendar. 

### Key Findings:
1. **Board Member Email from Sarah Jenkins (Chair)**: Sarah requested moving Friday's prep sync from 10:00 AM to 2:30 PM due to a flight schedule conflict.
2. **Calendar Conflict Check**: Your calendar is currently free between 2:00 PM and 4:15 PM on Friday, honoring your preference for a 15-minute buffer after your 1:00 PM product review.
3. **Pending Action**: I have staged a calendar update and drafted a confirmation email to Sarah.

Please review the proposed update in the **Approval Center** below or click **Approve** to execute.`,
    createdAt: '2026-09-30T14:30:25Z',
    agentId: 'agent_supervisor',
    agentName: 'Nexus Supervisor',
    executionSummary: [
      { id: 's1', title: 'Understanding intent & loading preferences', status: 'completed', timestamp: '2026-09-30T14:30:02Z', durationMs: 220 },
      { id: 's2', title: 'Memory retrieval: Found rule "15m meeting buffer"', status: 'completed', timestamp: '2026-09-30T14:30:05Z', durationMs: 180 },
      { id: 's3', title: 'Delegated to CommsAgent -> MCP Gmail search', status: 'completed', timestamp: '2026-09-30T14:30:12Z', durationMs: 650 },
      { id: 's4', title: 'Delegated to CalendarAgent -> Query free-busy slots', status: 'completed', timestamp: '2026-09-30T14:30:18Z', durationMs: 420 },
      { id: 's5', title: 'Staged Human-in-the-Loop approval for calendar move', status: 'completed', timestamp: '2026-09-30T14:30:22Z', durationMs: 140 },
    ],
    toolCalls: [
      {
        id: 'tc_1',
        name: 'gmail_search_messages',
        server: 'mcp-gmail',
        input: { query: 'from:board.org is:unread newer_than:3d' },
        status: 'success',
        durationMs: 480,
      },
      {
        id: 'tc_2',
        name: 'calendar_check_availability',
        server: 'mcp-calendar',
        input: { date: '2026-10-02', windowStart: '13:00', windowEnd: '17:00' },
        status: 'success',
        durationMs: 380,
      },
      {
        id: 'tc_3',
        name: 'calendar_update_event',
        server: 'mcp-calendar',
        input: { eventId: 'evt_board_prep_093', newStart: '2026-10-02T14:30:00Z', newEnd: '2026-10-02T15:30:00Z' },
        status: 'requires_approval',
        durationMs: 120,
      },
    ],
    approvalRequestId: 'appr_1',
  },
];

export const MOCK_ACTIVE_RUN: AgentRun = {
  id: 'run_active_102',
  conversationId: 'conv_1',
  agentId: 'agent_supervisor',
  agentName: 'Nexus Supervisor',
  taskTitle: 'Executive Inbox & Calendar Harmonization',
  status: 'running',
  startedAt: '2026-09-30T14:30:00Z',
  currentStepIndex: 3,
  steps: [
    {
      id: 'step_1',
      name: 'Intent Classification & Memory Lookup',
      type: 'memory_retrieval',
      agentName: 'Supervisor',
      summary: 'Retrieved 3 user preferences regarding meeting transitions and board members',
      status: 'completed',
      startedAt: '2026-09-30T14:30:01Z',
      completedAt: '2026-09-30T14:30:03Z',
      durationMs: 410,
    },
    {
      id: 'step_2',
      name: 'Query Board Threads via MCP Gmail',
      type: 'tool_execution',
      agentName: 'CommsAgent',
      summary: 'Found 1 high-priority email from Sarah Jenkins regarding Friday scheduling',
      status: 'completed',
      startedAt: '2026-09-30T14:30:03Z',
      completedAt: '2026-09-30T14:30:08Z',
      durationMs: 650,
      toolCall: {
        id: 'tc_g1',
        name: 'gmail_search_messages',
        server: 'mcp-gmail',
        input: { query: 'from:sarah@board.org label:INBOX' },
        status: 'success',
        durationMs: 480,
      },
    },
    {
      id: 'step_3',
      name: 'Verify Availability on Calendar',
      type: 'tool_execution',
      agentName: 'CalendarAgent',
      summary: 'Identified conflict-free window 14:00 - 16:15 with 15m safety margins',
      status: 'completed',
      startedAt: '2026-09-30T14:30:08Z',
      completedAt: '2026-09-30T14:30:14Z',
      durationMs: 420,
      toolCall: {
        id: 'tc_c1',
        name: 'calendar_check_availability',
        server: 'mcp-calendar',
        input: { timeMin: '2026-10-02T13:00:00Z', timeMax: '2026-10-02T18:00:00Z' },
        status: 'success',
        durationMs: 380,
      },
    },
    {
      id: 'step_4',
      name: 'Human Approval Gate: Reschedule Meeting',
      type: 'approval_wait',
      agentName: 'Supervisor',
      summary: 'Awaiting human authorization before sending calendar update to Sarah Jenkins',
      status: 'active',
      startedAt: '2026-09-30T14:30:15Z',
    },
    {
      id: 'step_5',
      name: 'Dispatch Confirmation Email & Synthesis',
      type: 'synthesis',
      agentName: 'CommsAgent',
      summary: 'Will transmit draft confirmation once approved by user',
      status: 'pending',
      startedAt: '2026-09-30T14:30:20Z',
    },
  ],
  tokenUsage: {
    promptTokens: 1840,
    completionTokens: 420,
    totalTokens: 2260,
    estimatedCostUsd: 0.0094,
  },
};

export const MOCK_CONNECTED_APPS: ConnectedApp[] = [
  {
    id: 'app_gmail',
    type: 'gmail',
    name: 'Gmail Workspace',
    description: 'Read unread threads, compose drafts, archive emails, and send approved communications.',
    icon: 'mail',
    status: 'connected',
    accountEmail: 'ceo@nexusai.enterprise',
    mcpServerName: 'mcp-server-gmail',
    mcpServerEndpoint: 'stdio://apps/api/mcp/servers/gmail_server.py',
    scopes: [
      { name: 'gmail.readonly', description: 'Read emails and metadata', isGranted: true },
      { name: 'gmail.compose', description: 'Create drafts and staging payloads', isGranted: true },
      { name: 'gmail.send', description: 'Send external messages with human confirmation', isGranted: true },
    ],
    toolsProvided: ['gmail_search_messages', 'gmail_get_thread', 'gmail_create_draft', 'gmail_send_message'],
    lastSyncedAt: '2026-09-30T14:25:00Z',
  },
  {
    id: 'app_calendar',
    type: 'google_calendar',
    name: 'Google Calendar',
    description: 'Executive agenda tracking, conflict-free scheduling, attendee invites, and meeting buffers.',
    icon: 'calendar',
    status: 'connected',
    accountEmail: 'ceo@nexusai.enterprise',
    mcpServerName: 'mcp-server-calendar',
    mcpServerEndpoint: 'stdio://apps/api/mcp/servers/calendar_server.py',
    scopes: [
      { name: 'calendar.events.readonly', description: 'Check availability and events', isGranted: true },
      { name: 'calendar.events', description: 'Create, modify, and delete calendar invites', isGranted: true },
    ],
    toolsProvided: ['calendar_list_events', 'calendar_check_availability', 'calendar_create_event', 'calendar_update_event'],
    lastSyncedAt: '2026-09-30T14:20:00Z',
  },
  {
    id: 'app_telegram',
    type: 'telegram',
    name: 'Telegram Bot',
    description: 'Executive mobile alerts, urgent message relay, and remote approval confirmations.',
    icon: 'send',
    status: 'connected',
    accountHandle: '@NexusChiefOfStaffBot',
    mcpServerName: 'mcp-server-telegram',
    scopes: [
      { name: 'bot.messages.read', description: 'Receive operator commands', isGranted: true },
      { name: 'bot.messages.send', description: 'Dispatch notifications and alerts', isGranted: true },
    ],
    toolsProvided: ['telegram_send_direct_message', 'telegram_post_channel_update', 'telegram_get_recent_chats'],
    lastSyncedAt: '2026-09-30T14:15:00Z',
  },
  {
    id: 'app_browser',
    type: 'browser_playwright',
    name: 'Headless Browser (Playwright)',
    description: 'Autonomous web navigation, data extraction, authenticated portal operations, and screenshots.',
    icon: 'globe',
    status: 'connected',
    mcpServerName: 'mcp-server-playwright',
    mcpServerEndpoint: 'stdio://node_modules/@modelcontextprotocol/server-playwright',
    scopes: [
      { name: 'sandbox.headless_browser', description: 'Execute sandboxed Chromium sessions', isGranted: true },
      { name: 'sandbox.screenshot', description: 'Capture viewport image traces', isGranted: true },
    ],
    toolsProvided: ['browser_navigate', 'browser_extract_text', 'browser_click_element', 'browser_take_screenshot'],
    lastSyncedAt: '2026-09-30T14:00:00Z',
  },
  {
    id: 'app_slack',
    type: 'slack',
    name: 'Slack Enterprise',
    description: 'Team channel monitoring, mentions triage, and thread summarization.',
    icon: 'hash',
    status: 'disconnected',
    mcpServerName: 'mcp-server-slack',
    scopes: [
      { name: 'channels:read', description: 'View public channels', isGranted: false },
      { name: 'chat:write', description: 'Post updates', isGranted: false },
    ],
    toolsProvided: ['slack_post_message', 'slack_read_channel'],
  },
  {
    id: 'app_notion',
    type: 'notion',
    name: 'Notion Workspace',
    description: 'Company documentation, weekly OKR tracking, and meeting minutes synchronization.',
    icon: 'book-open',
    status: 'disconnected',
    mcpServerName: 'mcp-server-notion',
    scopes: [
      { name: 'pages:read', description: 'Read company wiki', isGranted: false },
    ],
    toolsProvided: ['notion_search', 'notion_append_block'],
  },
];

export const MOCK_MEMORIES: Memory[] = [
  {
    id: 'mem_1',
    category: 'preference',
    title: 'Executive Calendar Buffer Rule',
    content: 'Always reserve a mandatory 15-minute buffer between meetings. Never schedule back-to-back external calls without explicit permission.',
    source: 'user_manual',
    confidence: 1.0,
    tags: ['calendar', 'rules', 'executive-buffer'],
    accessCount: 42,
    lastAccessedAt: '2026-09-30T14:30:05Z',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-20T10:00:00Z',
    pinned: true,
    metadata: { verifiedByUser: true },
  },
  {
    id: 'mem_2',
    category: 'preference',
    title: 'Communication Brevity Standard',
    content: 'Keep external email drafts under 4 sentences whenever feasible. Emphasize bullet points and explicit call-to-actions over conversational filler.',
    source: 'user_manual',
    confidence: 1.0,
    tags: ['comms', 'email-style', 'tone'],
    accessCount: 68,
    lastAccessedAt: '2026-09-30T14:30:02Z',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-15T10:00:00Z',
    pinned: true,
    metadata: { verifiedByUser: true },
  },
  {
    id: 'mem_3',
    category: 'semantic',
    title: 'Board Chair Contact & Profile',
    content: 'Sarah Jenkins is the primary Board Chair. Her email is sarah@board.org. Her preferred timezone is US/Eastern and she prefers updates via calendar invitations rather than long email threads.',
    source: 'email',
    confidence: 0.98,
    tags: ['contacts', 'board', 'vip'],
    accessCount: 23,
    lastAccessedAt: '2026-09-30T14:30:03Z',
    createdAt: '2026-09-03T12:00:00Z',
    updatedAt: '2026-09-28T09:00:00Z',
    pinned: false,
    metadata: { verifiedByUser: true, vectorId: 'vec_7749' },
  },
  {
    id: 'mem_4',
    category: 'procedural',
    title: 'Quarterly Board Meeting Prep SOP',
    content: 'Before quarterly board meetings: 1) Verify all financial deck slides are finalized in Drive, 2) Send calendar reminders 48h prior, 3) Prepare 1-page executive summary.',
    source: 'chat',
    confidence: 0.94,
    tags: ['sop', 'board', 'process'],
    accessCount: 12,
    lastAccessedAt: '2026-09-25T16:00:00Z',
    createdAt: '2026-09-10T14:00:00Z',
    updatedAt: '2026-09-10T14:00:00Z',
    pinned: false,
    metadata: { verifiedByUser: true, vectorId: 'vec_8812' },
  },
  {
    id: 'mem_5',
    category: 'episodic',
    title: 'Rescheduled Q3 Strategy Session Recap',
    content: 'On Sept 22, the CEO requested moving the strategy sync with product leadership to accommodate a customer crisis. Successfully notified 6 directors without friction.',
    source: 'task_result',
    confidence: 0.89,
    tags: ['recap', 'history', 'strategy'],
    accessCount: 5,
    lastAccessedAt: '2026-09-22T18:00:00Z',
    createdAt: '2026-09-22T18:00:00Z',
    updatedAt: '2026-09-22T18:00:00Z',
    pinned: false,
    metadata: { conversationId: 'conv_old_82' },
  },
];

export const MOCK_TASKS: ScheduledTask[] = [
  {
    id: 'task_1',
    title: 'Daily 8:00 AM Executive Morning Briefing',
    description: 'Autonomous scan of VIP email threads, calendar conflicts for the day, and high-impact industry headlines. Transmits summary to Telegram.',
    assignedAgentId: 'agent_supervisor',
    assignedAgentName: 'Nexus Supervisor',
    schedule: {
      type: 'cron',
      cronExpression: '0 8 * * 1-5',
      timezone: 'America/New_York',
      nextExecutionTime: '2026-10-01T08:00:00Z',
      lastExecutionTime: '2026-09-30T08:00:00Z',
    },
    status: 'scheduled',
    enabled: true,
    priority: 'high',
    requiresHumanApproval: false,
    targetMcpServers: ['mcp-gmail', 'mcp-calendar', 'mcp-telegram'],
    lastRuns: [
      { runId: 'run_b_1', timestamp: '2026-09-30T08:01:14Z', status: 'success', durationMs: 4120, summary: 'Sent 4-bullet executive briefing to Telegram.' },
      { runId: 'run_b_2', timestamp: '2026-09-29T08:01:05Z', status: 'success', durationMs: 3890, summary: 'Identified 1 meeting overlap and alerted user.' },
    ],
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-30T08:01:15Z',
  },
  {
    id: 'task_2',
    title: 'Friday Afternoon Calendar Cleanup & Optimization',
    description: 'Audits upcoming week calendar for missing meeting links, back-to-back violations, and unsolicited cold invites.',
    assignedAgentId: 'agent_calendar',
    assignedAgentName: 'Calendar Agent',
    schedule: {
      type: 'cron',
      cronExpression: '0 16 * * 5',
      timezone: 'America/New_York',
      nextExecutionTime: '2026-10-02T16:00:00Z',
      lastExecutionTime: '2026-09-25T16:00:00Z',
    },
    status: 'scheduled',
    enabled: true,
    priority: 'medium',
    requiresHumanApproval: true,
    targetMcpServers: ['mcp-calendar'],
    lastRuns: [
      { runId: 'run_c_1', timestamp: '2026-09-25T16:02:10Z', status: 'success', durationMs: 2750, summary: 'Suggested inserting 2 buffer blocks; approved by user.' },
    ],
    createdAt: '2026-09-05T00:00:00Z',
    updatedAt: '2026-09-25T16:02:10Z',
  },
  {
    id: 'task_3',
    title: 'Competitor Pricing & Changelog Monitor',
    description: 'Uses Playwright MCP to visit 3 competitor pricing pages and GitHub release feeds, detecting stealth tier shifts.',
    assignedAgentId: 'agent_browser',
    assignedAgentName: 'Browser Agent',
    schedule: {
      type: 'interval',
      intervalMinutes: 720,
      timezone: 'America/New_York',
      nextExecutionTime: '2026-09-30T23:00:00Z',
      lastExecutionTime: '2026-09-30T11:00:00Z',
    },
    status: 'running',
    enabled: true,
    priority: 'low',
    requiresHumanApproval: false,
    targetMcpServers: ['mcp-playwright'],
    lastRuns: [
      { runId: 'run_p_1', timestamp: '2026-09-30T11:03:40Z', status: 'success', durationMs: 8420, summary: 'No pricing adjustments detected across 3 targets.' },
    ],
    createdAt: '2026-09-12T00:00:00Z',
    updatedAt: '2026-09-30T11:03:40Z',
  },
  {
    id: 'task_4',
    title: 'Nightly Memory Deduplication & Vector Prune',
    description: 'Distills recent episodic runs, computes cosine similarity between overlapping memory facts, and purges stale context.',
    assignedAgentId: 'agent_supervisor',
    assignedAgentName: 'Nexus Supervisor',
    schedule: {
      type: 'cron',
      cronExpression: '0 2 * * *',
      timezone: 'America/New_York',
      nextExecutionTime: '2026-10-01T02:00:00Z',
      lastExecutionTime: '2026-09-30T02:00:00Z',
    },
    status: 'completed',
    enabled: true,
    priority: 'low',
    requiresHumanApproval: false,
    targetMcpServers: ['core'],
    lastRuns: [
      { runId: 'run_m_1', timestamp: '2026-09-30T02:01:50Z', status: 'success', durationMs: 1980, summary: 'Merged 3 redundant contact fragments into verified profiles.' },
    ],
    createdAt: '2026-09-15T00:00:00Z',
    updatedAt: '2026-09-30T02:01:50Z',
  },
];

export const MOCK_APPROVALS: ApprovalRequest[] = [
  {
    id: 'appr_1',
    runId: 'run_active_102',
    agentId: 'agent_calendar',
    agentName: 'Calendar Agent',
    impact: 'medium',
    status: 'pending',
    title: 'Reschedule Board Prep Meeting with Sarah Jenkins',
    explanation: 'Sarah Jenkins (Board Chair) emailed requesting to shift Friday prep sync to 2:30 PM. Moving this event updates Google Calendar invites for 3 attendees.',
    actionPayload: {
      service: 'calendar',
      action: 'calendar_update_event',
      target: 'Sarah Jenkins (sarah@board.org) + 2 attendees',
      parameters: {
        eventId: 'evt_board_prep_093',
        title: 'Q3 Board Preparation Sync',
        newStart: '2026-10-02T14:30:00-04:00',
        newEnd: '2026-10-02T15:30:00-04:00',
      },
      diff: {
        before: {
          time: 'Friday, Oct 2, 2026 at 10:00 AM - 11:00 AM EDT',
          status: 'Confirmed',
          bufferViolated: false,
        },
        after: {
          time: 'Friday, Oct 2, 2026 at 2:30 PM - 3:30 PM EDT',
          status: 'Pending Approval',
          bufferViolated: false,
        },
      },
    },
    requestedAt: '2026-09-30T14:30:22Z',
    expiresAt: '2026-10-01T14:30:22Z',
  },
  {
    id: 'appr_2',
    runId: 'run_comms_94',
    agentId: 'agent_comms',
    agentName: 'Comms Agent',
    impact: 'high',
    status: 'pending',
    title: 'Send Confirmation & Board Deck Draft to Chair',
    explanation: 'Sends drafted response email with Google Drive deck attachment link to sarah@board.org on your behalf.',
    actionPayload: {
      service: 'gmail',
      action: 'gmail_send_message',
      target: 'sarah@board.org',
      parameters: {
        to: ['sarah@board.org'],
        subject: 'Re: Friday Prep Meeting Timing + Q3 Deck',
        body: 'Hi Sarah,\n\n2:30 PM on Friday works perfectly. I have shifted the calendar invite accordingly.\n\nHere is the preliminary deck link for your review:\nhttps://drive.google.com/nexus/board-q3-draft\n\nBest,\nAlex',
      },
      diff: {
        after: {
          recipient: 'sarah@board.org',
          subject: 'Re: Friday Prep Meeting Timing + Q3 Deck',
          charCount: 185,
        },
      },
    },
    requestedAt: '2026-09-30T14:32:00Z',
    expiresAt: '2026-10-01T14:32:00Z',
  },
  {
    id: 'appr_3',
    runId: 'run_hist_21',
    agentId: 'agent_comms',
    agentName: 'Comms Agent',
    impact: 'medium',
    status: 'approved',
    title: 'Send Weekly Engineering Highlights to Telegram Channel',
    explanation: 'Dispatched automated 4-point progress recap to the internal Core Eng announcements channel.',
    actionPayload: {
      service: 'telegram',
      action: 'telegram_post_channel_update',
      target: '@NexusCoreDevTeam',
      parameters: { channelId: '-1002938491', messageCount: 1 },
    },
    requestedAt: '2026-09-29T17:00:00Z',
    expiresAt: '2026-09-30T17:00:00Z',
    decidedAt: '2026-09-29T17:04:12Z',
    decidedBy: 'Operator (Alex)',
    decisionNotes: 'Approved without edits.',
  },
];

export const MOCK_OBSERVABILITY_RUNS: ObservabilityRun[] = [
  {
    id: 'run_obs_981',
    agentId: 'agent_supervisor',
    agentName: 'Nexus Supervisor',
    taskTitle: 'Board Prep & Calendar Harmonization',
    status: 'running',
    startedAt: '2026-09-30T14:30:00Z',
    durationMs: 24500,
    toolsUsed: ['gmail_search_messages', 'calendar_check_availability', 'calendar_update_event'],
    toolCallCount: 3,
    metrics: {
      promptTokens: 1840,
      completionTokens: 420,
      totalTokens: 2260,
      estimatedCostUsd: 0.0094,
      tokensPerSecond: 94.2,
    },
    latency: {
      planningMs: 410,
      toolExecutionMs: 1450,
      modelInferenceMs: 1820,
      totalMs: 3680,
    },
    hasErrors: false,
    approvalRequired: true,
    approvalGranted: false,
  },
  {
    id: 'run_obs_980',
    agentId: 'agent_browser',
    agentName: 'Browser Agent',
    taskTitle: 'Competitor Changelog Scraping',
    status: 'completed',
    startedAt: '2026-09-30T11:00:00Z',
    completedAt: '2026-09-30T11:00:08Z',
    durationMs: 8420,
    toolsUsed: ['browser_navigate', 'browser_extract_text', 'browser_take_screenshot'],
    toolCallCount: 6,
    metrics: {
      promptTokens: 4120,
      completionTokens: 680,
      totalTokens: 4800,
      estimatedCostUsd: 0.0192,
      tokensPerSecond: 82.5,
    },
    latency: {
      planningMs: 620,
      toolExecutionMs: 6100,
      modelInferenceMs: 1700,
      totalMs: 8420,
    },
    hasErrors: false,
    approvalRequired: false,
  },
  {
    id: 'run_obs_979',
    agentId: 'agent_supervisor',
    agentName: 'Nexus Supervisor',
    taskTitle: 'Daily Morning Executive Briefing',
    status: 'completed',
    startedAt: '2026-09-30T08:00:00Z',
    completedAt: '2026-09-30T08:00:04Z',
    durationMs: 4120,
    toolsUsed: ['gmail_search_messages', 'calendar_list_events', 'telegram_send_direct_message'],
    toolCallCount: 3,
    metrics: {
      promptTokens: 2240,
      completionTokens: 510,
      totalTokens: 2750,
      estimatedCostUsd: 0.0112,
      tokensPerSecond: 104.3,
    },
    latency: {
      planningMs: 380,
      toolExecutionMs: 1950,
      modelInferenceMs: 1790,
      totalMs: 4120,
    },
    hasErrors: false,
    approvalRequired: false,
  },
  {
    id: 'run_obs_978',
    agentId: 'agent_comms',
    agentName: 'Comms Agent',
    taskTitle: 'Outreach Followup Draft Generation',
    status: 'failed',
    startedAt: '2026-09-29T16:20:00Z',
    completedAt: '2026-09-29T16:20:03Z',
    durationMs: 3100,
    toolsUsed: ['gmail_search_messages'],
    toolCallCount: 1,
    metrics: {
      promptTokens: 1120,
      completionTokens: 80,
      totalTokens: 1200,
      estimatedCostUsd: 0.0048,
      tokensPerSecond: 40.0,
    },
    latency: {
      planningMs: 320,
      toolExecutionMs: 2700,
      modelInferenceMs: 80,
      totalMs: 3100,
    },
    hasErrors: true,
    errorMessage: 'MCP Server "mcp-gmail" rate limit exceeded (HTTP 429)',
    approvalRequired: false,
  },
];

export const MOCK_SYSTEM_HEALTH: SystemHealthSummary = {
  activeRunsCount: 1,
  successRate24h: 96.8,
  averageLatencyMs: 3420,
  totalTokens24h: 184500,
  totalCost24hUsd: 0.842,
  pendingApprovalsCount: 2,
  connectedAppsCount: 4,
};

export const MOCK_SETTINGS: SystemSettings = {
  user: {
    name: 'Alex Vance',
    email: 'alex@nexusai.enterprise',
    timezone: 'America/New_York (UTC-4)',
    locale: 'en-US',
    preferredTone: 'executive',
    theme: 'dark',
  },
  model: {
    provider: 'gemini',
    modelId: 'gemini-3.8-flash',
    temperature: 0.2,
    maxOutputTokens: 4096,
    apiKeySet: true,
    streamingEnabled: true,
  },
  guardrails: {
    autonomyLevel: 'balanced',
    requireApprovalForEmailSend: true,
    requireApprovalForCalendarCreate: true,
    requireApprovalForTelegramSend: true,
    requireApprovalForBrowserActions: true,
    requireApprovalForFinancials: true,
    maxConcurrentAgents: 4,
    maxToolCallsPerRun: 15,
    dailyCostBudgetUsd: 25.0,
  },
  notifications: {
    emailAlerts: true,
    telegramAlerts: true,
    browserPush: false,
    notifyOnApprovalRequired: true,
    notifyOnTaskFailure: true,
    dailyDigestTime: '08:00',
  },
};
